// Generated by CoffeeScript 1.10.0
(function() {
  this.THIS = this;

  this.designWinSize = new cc.p(1280, 720);

  this.resolutionPolicy = cc.ResolutionPolicy.SHOW_ALL;

  this.winSize = cc.winSize;

  this.loadResourceDelay = 0;

  this.loadFinishDelay = 0;

  this.nextDialogDelay = 0.3;

  this.isCloseDialogOutside = true;

  this.musicState = true;

  this.difficult = {
    low: 0,
    middle: 1,
    high: 2
  };

  this.gameDifficult = this.difficult.low;

  this.gameMode = {
    classics: 0,
    challenge: 1,
    arcade: 2
  };

  this.highestRecord = {
    classics: 23,
    challenge: 18,
    arcade: 14
  };

  this.countDown = {
    classics: 0,
    challenge: 3,
    arcade: 3
  };

  this.maxError = 3;

  this.isRotation = false;

  this.rotationTime = 2;

  this.selectedNumberColor = cc.color(25, 200, 25, 255);

  this.numberCount = 6;

}).call(this);

//# sourceMappingURL=InitUtil.js.map
