// Generated by CoffeeScript 1.10.0

/*
  带关闭按钮的对话框
 */

(function() {
  this.Dialog = cc.Layer.extend({
    dialogLayer: null,
    popDialog: null,
    btnClose: null,
    ctor: function() {
      this._super(cc.color(0, 0, 0, 0));
      this.initDialog();
      return this.initCloseBtn();
    },
    initDialog: function() {
      var stDialogBg;
      stDialogBg = new cc.Sprite(res.igDialogBg);
      this.dialogLayer = new cc.LayerColor(cc.color(0, 0, 0, 0), stDialogBg.width, stDialogBg.height);
      this.dialogLayer.attr({
        x: THIS.winSize.width / 2 - this.dialogLayer.width / 2,
        y: THIS.winSize.height / 2 - this.dialogLayer.height / 2
      });
      stDialogBg.attr({
        x: this.dialogLayer.width / 2,
        y: this.dialogLayer.height / 2
      });
      this.dialogLayer.addChild(stDialogBg, 0);
      this.popDialog = new PopDialog(this.dialogLayer, true, THIS.isCloseDialogOutside);
      return this.addChild(this.popDialog);
    },
    initCloseBtn: function() {
      var self;
      this.btnClose = new ccui.Button();
      this.btnClose.loadTextureNormal(res.igBtnClose, ccui.Widget.LOCAL_TEXTURE);
      this.btnClose.setPressedActionEnabled(true);
      this.btnClose.attr({
        x: this.dialogLayer.width - 40,
        y: this.dialogLayer.height - 40
      });
      this.btnClose.setTouchEnabled(true);
      this.dialogLayer.addChild(this.btnClose, 5);
      self = this;
      return this.btnClose.addTouchEventListener(function(touch, event) {
        if (event === ccui.Widget.TOUCH_ENDED) {
          LogTool.c("点击关闭按钮");
          return self.popDialog.hidden(function() {
            return LogTool.c("关闭了对话框");
          });
        }
      }, this.btnClose);
    }
  });

}).call(this);

//# sourceMappingURL=Dialog.js.map
