// Generated by CoffeeScript 1.10.0

/*
  返回游戏确认对话框
 */

(function() {
  this.BackConfirmDialog = Dialog.extend({
    btnOk: null,
    btnCancel: null,
    funOk: null,
    funCancel: null,
    ctor: function() {
      this._super();
      this.initBtnOk();
      return this.initBtnCancel();
    },
    initBtnOk: function() {
      var self;
      this.btnOk = new ccui.Button();
      this.btnOk.loadTextureNormal(res.igBtnOk, ccui.Widget.LOCAL_TEXTURE);
      this.btnOk.setPressedActionEnabled(true);
      this.btnOk.setTouchEnabled(true);
      this.btnOk.attr({
        x: this.dialogLayer.width / 2,
        y: this.dialogLayer.height / 2 + this.btnOk.height / 2 + 25
      });
      this.dialogLayer.addChild(this.btnOk, 5);
      self = this;
      return this.btnOk.addTouchEventListener(function(touch, event) {
        var error, error1;
        if (event === ccui.Widget.TOUCH_ENDED) {
          LogTool.c("点击确认关闭按钮");
          try {
            if (typeof self.funOk === "function") {
              self.funOk();
            } else {
              LogTool.c("funOk is not a function");
            }
          } catch (error1) {
            error = error1;
            LogTool.c(error);
          }
          self.popDialog.hidden();
          return cc.director.popScene();
        }
      }, this.btnOk);
    },
    initBtnCancel: function() {
      var self;
      this.btnCancel = new ccui.Button();
      this.btnCancel.loadTextureNormal(res.igBtnCancel, ccui.Widget.LOCAL_TEXTURE);
      this.btnCancel.setPressedActionEnabled(true);
      this.btnCancel.setTouchEnabled(true);
      this.btnCancel.attr({
        x: this.dialogLayer.width / 2,
        y: this.dialogLayer.height / 2 - this.btnCancel.height / 2 - 25
      });
      this.dialogLayer.addChild(this.btnCancel, 5);
      self = this;
      return this.btnCancel.addTouchEventListener(function(touch, event) {
        var error, error1;
        if (event === ccui.Widget.TOUCH_ENDED) {
          LogTool.c("点击取消按钮");
          try {
            if (typeof self.funCancel === "function") {
              self.funCancel();
            } else {
              LogTool.c("funCancel is not a function");
            }
          } catch (error1) {
            error = error1;
            LogTool.c(error);
          }
          return self.popDialog.hidden();
        }
      }, this.btnCancel);
    }
  });

}).call(this);

//# sourceMappingURL=BackConfirmDialog.js.map
