// Generated by CoffeeScript 1.10.0

/*
  游戏设置对话框
 */

(function() {
  this.GameSettingDialog = Dialog.extend({
    btnMusic: null,
    btnDifficult: null,
    ctor: function() {
      this._super();
      this.initBtnMusic();
      return this.initBtnDifficult();
    },
    initBtnMusic: function() {
      var self;
      this.btnMusic = new ccui.Button();
      this.btnMusic.loadTextureNormal(res.igBtnMusic, ccui.Widget.LOCAL_TEXTURE);
      this.btnMusic.setPressedActionEnabled(true);
      this.btnMusic.setTouchEnabled(true);
      this.btnMusic.attr({
        x: this.dialogLayer.width / 2,
        y: this.dialogLayer.height / 2 + this.btnMusic.height / 2 + 25
      });
      this.dialogLayer.addChild(this.btnMusic, 5);
      self = this;
      return this.btnMusic.addTouchEventListener(function(touch, event) {
        if (event === ccui.Widget.TOUCH_ENDED) {
          LogTool.c("点击音乐按钮");
          self.popDialog.hidden();
          return self.scheduleOnce(function() {
            return self.addChild(new MusicSettingDialog(), 5);
          }, THIS.nextDialogDelay);
        }
      }, this.btnMusic);
    },
    initBtnDifficult: function() {
      var self;
      this.btnDifficult = new ccui.Button();
      this.btnDifficult.loadTextureNormal(res.igBtnDifficult, ccui.Widget.LOCAL_TEXTURE);
      this.btnDifficult.setPressedActionEnabled(true);
      this.btnDifficult.setTouchEnabled(true);
      this.btnDifficult.attr({
        x: this.dialogLayer.width / 2,
        y: this.dialogLayer.height / 2 - this.btnDifficult.height / 2 - 25
      });
      this.dialogLayer.addChild(this.btnDifficult, 5);
      self = this;
      return this.btnDifficult.addTouchEventListener(function(touch, event) {
        if (event === ccui.Widget.TOUCH_ENDED) {
          LogTool.c("点击游戏设置按钮");
          self.popDialog.hidden();
          return self.scheduleOnce(function() {
            return self.addChild(new DifficultSettingDialog(), 5);
          }, THIS.nextDialogDelay);
        }
      }, this.btnDifficult);
    }
  });

}).call(this);

//# sourceMappingURL=GameSettingDialog.js.map
