// Generated by CoffeeScript 1.10.0
(function() {
  this.LoadingLayer = cc.Layer.extend({
    stMainBg: null,
    stTitle: null,
    stGarlic: null,
    stTipFrame: null,
    lbTip: null,
    stSlider: null,
    pbLoading: null,
    ctor: function() {
      var size;
      this._super();
      size = cc.winSize;
      this.stMainBg = new cc.Sprite(res.igMainBg);
      this.stMainBg.attr({
        x: size.width / 2,
        y: size.height / 2
      });
      this.addChild(this.stMainBg, 0);
      return true;
    }
  });

}).call(this);

//# sourceMappingURL=loadingPage.js.map
