// Generated by CoffeeScript 1.10.0

/*
  游戏重来
 */

(function() {
  this.RegameDialog = Dialog.extend({
    btnAgain: null,
    btnBack: null,
    btnHighAgain: null,
    funOk: null,
    funBack: null,
    isHigh: null,
    ctor: function(_isHigh) {
      this._super();
      this.isHigh = _isHigh;
      if (this.isHigh) {
        this.initBtnHighAgain();
        this.initHighTip();
      } else {
        this.initBtnAgain();
      }
      return this.initBtnBack();
    },
    initBtnAgain: function() {
      var self;
      this.btnAgain = new ccui.Button();
      this.btnAgain.loadTextureNormal(res.igBtnAgain, ccui.Widget.LOCAL_TEXTURE);
      this.btnAgain.setPressedActionEnabled(true);
      this.btnAgain.setTouchEnabled(true);
      this.btnAgain.attr({
        x: this.dialogLayer.width / 2,
        y: this.dialogLayer.height / 2 + this.btnAgain.height / 2 + 25
      });
      this.dialogLayer.addChild(this.btnAgain, 5);
      self = this;
      return this.btnAgain.addTouchEventListener(function(touch, event) {
        if (event === ccui.Widget.TOUCH_ENDED) {
          LogTool.c("点击重来按钮");
          return self.popDialog.hidden(self.funOk);
        }
      }, this.btnAgain);
    },
    initBtnHighAgain: function() {
      var self;
      this.btnAgain = new ccui.Button();
      this.btnAgain.loadTextureNormal(res.igBtnHighAgain, ccui.Widget.LOCAL_TEXTURE);
      this.btnAgain.setPressedActionEnabled(true);
      this.btnAgain.setTouchEnabled(true);
      this.btnAgain.attr({
        x: this.dialogLayer.width / 2,
        y: this.dialogLayer.height / 2 + this.btnAgain.height / 2 + 25
      });
      this.dialogLayer.addChild(this.btnAgain, 5);
      self = this;
      return this.btnAgain.addTouchEventListener(function(touch, event) {
        if (event === ccui.Widget.TOUCH_ENDED) {
          LogTool.c("点击最高分重来按钮");
          return self.popDialog.hidden(self.funOk);
        }
      }, this.btnAgain);
    },
    initBtnBack: function() {
      var self;
      this.btnBack = new ccui.Button();
      this.btnBack.loadTextureNormal(res.igBtnBack, ccui.Widget.LOCAL_TEXTURE);
      this.btnBack.setPressedActionEnabled(true);
      this.btnBack.setTouchEnabled(true);
      this.btnBack.attr({
        x: this.dialogLayer.width / 2,
        y: this.dialogLayer.height / 2 - this.btnBack.height / 2 - 25
      });
      this.dialogLayer.addChild(this.btnBack, 5);
      self = this;
      return this.btnBack.addTouchEventListener(function(touch, event) {
        var error, error1;
        if (event === ccui.Widget.TOUCH_ENDED) {
          LogTool.c("点击返回按钮");
          try {
            if (typeof self.funBack === "function") {
              self.funBack();
            } else {
              LogTool.c("funBack is not a function");
            }
          } catch (error1) {
            error = error1;
            LogTool.c(error);
          }
          return self.popDialog.hidden();
        }
      }, this.btnBack);
    },
    initHighTip: function() {
      var best, flower, high;
      flower = new cc.Sprite(res.igFlower);
      flower.attr({
        x: this.dialogLayer.width - flower.width / 2 - 60,
        y: this.dialogLayer.height - flower.height / 2 - 20
      });
      this.dialogLayer.addChild(flower, 0);
      best = new cc.LabelTTF("you are the best ... ...");
      best.fontSize = 30;
      best.fillStyle = cc.color(0, 0, 0, 255);
      best.attr({
        x: flower.x - best.width / 2 - flower.width / 2 - 20,
        y: this.dialogLayer.height - flower.height / 2 - 10
      });
      this.dialogLayer.addChild(best, 0);
      high = new cc.LabelTTF("最高分~~~耶耶~~~");
      high.fontSize = 30;
      high.fillStyle = cc.color(0, 0, 0, 255);
      high.attr({
        x: this.dialogLayer.width - high.width / 2 - 80,
        y: 50
      });
      return this.dialogLayer.addChild(high, 0);
    }
  });

}).call(this);

//# sourceMappingURL=RegameDialog.js.map
